// ================================================================================
// File automatically generated by katie.exe v1.5
// http://www.console-dev.de
// 
// WARNING: All changes made in this file will be lost!
// ================================================================================

#ifndef SRC_GFX_RESOURCEDATA_H
#define SRC_GFX_RESOURCEDATA_H

#ifdef __cplusplus
	extern "C"{
#endif

// src/gfx/raw/carre.raw
#define RES_CARRE_RAW	0
#define RES_CARRE_RAW_SIZE	128
#define RES_CARRE_RAW_SIZEPADDED	128
#define RES_CARRE_RAW_SIZE16	64
#define RES_CARRE_RAW_SIZE16PADDED	64
#define RES_CARRE_RAW_SIZE32	32
#define RES_CARRE_RAW_SIZE32PADDED	32

// src/gfx/raw/champ1.raw
#define RES_CHAMP1_RAW	128
#define RES_CHAMP1_RAW_SIZE	128
#define RES_CHAMP1_RAW_SIZEPADDED	128
#define RES_CHAMP1_RAW_SIZE16	64
#define RES_CHAMP1_RAW_SIZE16PADDED	64
#define RES_CHAMP1_RAW_SIZE32	32
#define RES_CHAMP1_RAW_SIZE32PADDED	32

// src/gfx/raw/champ2.raw
#define RES_CHAMP2_RAW	256
#define RES_CHAMP2_RAW_SIZE	128
#define RES_CHAMP2_RAW_SIZEPADDED	128
#define RES_CHAMP2_RAW_SIZE16	64
#define RES_CHAMP2_RAW_SIZE16PADDED	64
#define RES_CHAMP2_RAW_SIZE32	32
#define RES_CHAMP2_RAW_SIZE32PADDED	32

// src/gfx/raw/cursor1.raw
#define RES_CURSOR1_RAW	384
#define RES_CURSOR1_RAW_SIZE	256
#define RES_CURSOR1_RAW_SIZEPADDED	256
#define RES_CURSOR1_RAW_SIZE16	128
#define RES_CURSOR1_RAW_SIZE16PADDED	128
#define RES_CURSOR1_RAW_SIZE32	64
#define RES_CURSOR1_RAW_SIZE32PADDED	64

// src/gfx/raw/imgBackground.map
#define RES_IMGBACKGROUND_MAP	640
#define RES_IMGBACKGROUND_MAP_SIZE	1280
#define RES_IMGBACKGROUND_MAP_SIZEPADDED	1280
#define RES_IMGBACKGROUND_MAP_SIZE16	640
#define RES_IMGBACKGROUND_MAP_SIZE16PADDED	640
#define RES_IMGBACKGROUND_MAP_SIZE32	320
#define RES_IMGBACKGROUND_MAP_SIZE32PADDED	320

// src/gfx/raw/imgBackground.raw
#define RES_IMGBACKGROUND_RAW	1920
#define RES_IMGBACKGROUND_RAW_SIZE	24576
#define RES_IMGBACKGROUND_RAW_SIZEPADDED	24576
#define RES_IMGBACKGROUND_RAW_SIZE16	12288
#define RES_IMGBACKGROUND_RAW_SIZE16PADDED	12288
#define RES_IMGBACKGROUND_RAW_SIZE32	6144
#define RES_IMGBACKGROUND_RAW_SIZE32PADDED	6144

// src/gfx/raw/imgBackground2.map
#define RES_IMGBACKGROUND2_MAP	26496
#define RES_IMGBACKGROUND2_MAP_SIZE	1280
#define RES_IMGBACKGROUND2_MAP_SIZEPADDED	1280
#define RES_IMGBACKGROUND2_MAP_SIZE16	640
#define RES_IMGBACKGROUND2_MAP_SIZE16PADDED	640
#define RES_IMGBACKGROUND2_MAP_SIZE32	320
#define RES_IMGBACKGROUND2_MAP_SIZE32PADDED	320

// src/gfx/raw/imgBackground2.raw
#define RES_IMGBACKGROUND2_RAW	27776
#define RES_IMGBACKGROUND2_RAW_SIZE	4608
#define RES_IMGBACKGROUND2_RAW_SIZEPADDED	4608
#define RES_IMGBACKGROUND2_RAW_SIZE16	2304
#define RES_IMGBACKGROUND2_RAW_SIZE16PADDED	2304
#define RES_IMGBACKGROUND2_RAW_SIZE32	1152
#define RES_IMGBACKGROUND2_RAW_SIZE32PADDED	1152

// src/gfx/raw/imgGamecover.map
#define RES_IMGGAMECOVER_MAP	32384
#define RES_IMGGAMECOVER_MAP_SIZE	1280
#define RES_IMGGAMECOVER_MAP_SIZEPADDED	1280
#define RES_IMGGAMECOVER_MAP_SIZE16	640
#define RES_IMGGAMECOVER_MAP_SIZE16PADDED	640
#define RES_IMGGAMECOVER_MAP_SIZE32	320
#define RES_IMGGAMECOVER_MAP_SIZE32PADDED	320

// src/gfx/raw/imgGamecover.raw
#define RES_IMGGAMECOVER_RAW	33664
#define RES_IMGGAMECOVER_RAW_SIZE	3200
#define RES_IMGGAMECOVER_RAW_SIZEPADDED	3200
#define RES_IMGGAMECOVER_RAW_SIZE16	1600
#define RES_IMGGAMECOVER_RAW_SIZE16PADDED	1600
#define RES_IMGGAMECOVER_RAW_SIZE32	800
#define RES_IMGGAMECOVER_RAW_SIZE32PADDED	800

// src/gfx/raw/monstre1.raw
#define RES_MONSTRE1_RAW	36864
#define RES_MONSTRE1_RAW_SIZE	256
#define RES_MONSTRE1_RAW_SIZEPADDED	256
#define RES_MONSTRE1_RAW_SIZE16	128
#define RES_MONSTRE1_RAW_SIZE16PADDED	128
#define RES_MONSTRE1_RAW_SIZE32	64
#define RES_MONSTRE1_RAW_SIZE32PADDED	64

// src/gfx/raw/niv1.map
#define RES_NIV1_MAP	37120
#define RES_NIV1_MAP_SIZE	1280
#define RES_NIV1_MAP_SIZEPADDED	1280
#define RES_NIV1_MAP_SIZE16	640
#define RES_NIV1_MAP_SIZE16PADDED	640
#define RES_NIV1_MAP_SIZE32	320
#define RES_NIV1_MAP_SIZE32PADDED	320

// src/gfx/raw/niv1.raw
#define RES_NIV1_RAW	38400
#define RES_NIV1_RAW_SIZE	960
#define RES_NIV1_RAW_SIZEPADDED	960
#define RES_NIV1_RAW_SIZE16	480
#define RES_NIV1_RAW_SIZE16PADDED	480
#define RES_NIV1_RAW_SIZE32	240
#define RES_NIV1_RAW_SIZE32PADDED	240

// src/gfx/raw/niv2.map
#define RES_NIV2_MAP	39360
#define RES_NIV2_MAP_SIZE	1280
#define RES_NIV2_MAP_SIZEPADDED	1280
#define RES_NIV2_MAP_SIZE16	640
#define RES_NIV2_MAP_SIZE16PADDED	640
#define RES_NIV2_MAP_SIZE32	320
#define RES_NIV2_MAP_SIZE32PADDED	320

// src/gfx/raw/niv2.raw
#define RES_NIV2_RAW	40640
#define RES_NIV2_RAW_SIZE	1984
#define RES_NIV2_RAW_SIZEPADDED	1984
#define RES_NIV2_RAW_SIZE16	992
#define RES_NIV2_RAW_SIZE16PADDED	992
#define RES_NIV2_RAW_SIZE32	496
#define RES_NIV2_RAW_SIZE32PADDED	496

// src/gfx/raw/osc_saw.raw
#define RES_OSC_SAW_RAW	42624
#define RES_OSC_SAW_RAW_SIZE	64
#define RES_OSC_SAW_RAW_SIZEPADDED	64
#define RES_OSC_SAW_RAW_SIZE16	32
#define RES_OSC_SAW_RAW_SIZE16PADDED	32
#define RES_OSC_SAW_RAW_SIZE32	16
#define RES_OSC_SAW_RAW_SIZE32PADDED	16

// src/gfx/raw/peach.raw
#define RES_PEACH_RAW	42688
#define RES_PEACH_RAW_SIZE	256
#define RES_PEACH_RAW_SIZEPADDED	256
#define RES_PEACH_RAW_SIZE16	128
#define RES_PEACH_RAW_SIZE16PADDED	128
#define RES_PEACH_RAW_SIZE32	64
#define RES_PEACH_RAW_SIZE32PADDED	64

// src/gfx/raw/screen.pal
#define RES_SCREEN_PAL	42944
#define RES_SCREEN_PAL_SIZE	512
#define RES_SCREEN_PAL_SIZEPADDED	512
#define RES_SCREEN_PAL_SIZE16	256
#define RES_SCREEN_PAL_SIZE16PADDED	256
#define RES_SCREEN_PAL_SIZE32	128
#define RES_SCREEN_PAL_SIZE32PADDED	128

// src/gfx/raw/sprites.pal
#define RES_SPRITES_PAL	43456
#define RES_SPRITES_PAL_SIZE	32
#define RES_SPRITES_PAL_SIZEPADDED	32
#define RES_SPRITES_PAL_SIZE16	16
#define RES_SPRITES_PAL_SIZE16PADDED	16
#define RES_SPRITES_PAL_SIZE32	8
#define RES_SPRITES_PAL_SIZE32PADDED	8

// src/gfx/raw/text.map
#define RES_TEXT_MAP	43488
#define RES_TEXT_MAP_SIZE	320
#define RES_TEXT_MAP_SIZEPADDED	320
#define RES_TEXT_MAP_SIZE16	160
#define RES_TEXT_MAP_SIZE16PADDED	160
#define RES_TEXT_MAP_SIZE32	80
#define RES_TEXT_MAP_SIZE32PADDED	80

// src/gfx/raw/text.raw
#define RES_TEXT_RAW	43808
#define RES_TEXT_RAW_SIZE	6016
#define RES_TEXT_RAW_SIZEPADDED	6016
#define RES_TEXT_RAW_SIZE16	3008
#define RES_TEXT_RAW_SIZE16PADDED	3008
#define RES_TEXT_RAW_SIZE32	1504
#define RES_TEXT_RAW_SIZE32PADDED	1504

// src/gfx/raw/tortue.raw
#define RES_TORTUE_RAW	49824
#define RES_TORTUE_RAW_SIZE	256
#define RES_TORTUE_RAW_SIZEPADDED	256
#define RES_TORTUE_RAW_SIZE16	128
#define RES_TORTUE_RAW_SIZE16PADDED	128
#define RES_TORTUE_RAW_SIZE32	64
#define RES_TORTUE_RAW_SIZE32PADDED	64


#define ResData(_identifier)	((const void*)&__ResourceData__[_identifier])
#define ResData8(_identifier)	((const unsigned char*)&__ResourceData__[_identifier])
#define ResData8X(_identifier, _index)	((const unsigned char*)&__ResourceData__[(_identifier)+(_index)])
#define ResData16(_identifier)	((const unsigned short*)&__ResourceData__[_identifier])
#define ResData16X(_identifier, _index)	((const unsigned short*)&__ResourceData__[(_identifier)+((_index)<<1)])
#define ResData32(_identifier)	((const unsigned long*)&__ResourceData__[_identifier])
#define ResData32X(_identifier, _index)	((const unsigned long*)&__ResourceData__[(_identifier)+((_index)<<2)])
#define ResDataType(_type, _identifier)	((const _type*)&__ResourceData__[_identifier])
#define ResDataTypeX(_type, _identifier, _index)	((const _type*)&__ResourceData__[(_identifier)+((_index)*sizeof(_type)])


extern const unsigned char __ResourceData__[];

#ifdef __cplusplus
	}
#endif

#endif // SRC_GFX_RESOURCEDATA_H

